trigger:
  - main
variables:
  azuresubscription: "AzureServiceConnection"
pool:
  vmImage: "ubuntu-latest"
stages:
  - stage: Terraform
    displayName: "Terraform Deployment"
    jobs:
      - job: ApplyTerraform
        steps:
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: '1.2.0'
          - task: TerraformCLI@2
            displayName: "Initialize Terraform"
            inputs:
              command: "init"
              workingDirectory: "Terraform"
          - task: TerraformCLI@2
            displayName: "Apply Terraform"
            inputs:
              command: "apply"
              workingDirectory: "Terraform"
              commandOptions: "-auto-approve"
